### ISSUE TITLE
Taille image adaptée à l’écran

### ISSUE THREAD

**Issue by lucarabistouille** [bible-sacy/bible-sacy.github.io#7]
Une fonctionnalité qui serait intéressante pour les liseuses électroniques.

Assez simple à réaliser [avec un peu de CSS](https://stackoverflow.com/questions/18934141/set-div-height-to-fit-to-the-browser-using-css). Peut-être le faire uniquement pour les liseuses avec un media query ?

**Comment by LGD-Fr** [comment]
Ou un paramètre activable à la demande (bouton ?).
